# Generated by Django 4.0.2 on 2022-03-09 07:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('venue_id_code', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('pin_code', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('open_timing', models.DateTimeField(blank=True, null=True)),
                ('close_timing', models.DateTimeField(blank=True, null=True)),
                ('entry_fee', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('ID_type', models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('Voter Card', 'Voter Card'), ('Pan Card', 'Pan Card')], default='Aadhar Card', max_length=20)),
                ('ID_number', models.CharField(max_length=50)),
                ('Num_ticket', models.IntegerField(default=0)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Online', max_length=20)),
                ('Trans_ID', models.CharField(max_length=50)),
                ('Total_amt', models.IntegerField(default=0)),
                ('entry_code', models.IntegerField(default=0)),
                ('QR_code', models.ImageField(blank=True, upload_to='')),
                ('Ticket_validation', models.BooleanField(default=True)),
                ('booking_time', models.DateTimeField(default=datetime.datetime(2022, 3, 9, 7, 26, 46, 965335))),
                ('Visiting_Date', models.DateTimeField(blank=True)),
                ('Ticket_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('qr_svg', models.CharField(blank=True, max_length=100000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue_id_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.venue')),
            ],
        ),
    ]
