# Generated by Django 4.0.2 on 2022-03-09 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 15, 52, 16, 51998)),
        ),
    ]
