# Generated by Django 4.0.2 on 2022-03-09 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_venue_desc_alter_ticket_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 4, 3, 5, 582879)),
        ),
        migrations.AlterField(
            model_name='venue',
            name='close_timing',
            field=models.TimeField(blank=True, default='04:03:05', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='open_timing',
            field=models.TimeField(blank=True, default='04:03:05', null=True),
        ),
    ]
